# Generated by Django 4.2.23 on 2025-06-28 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_booking_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='Guest phone', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('date', 'time', 'table'), name='unique_table_booking'),
        ),
    ]
