# Generated by Django 4.2.23 on 2025-06-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_booking_created_on_alter_booking_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
