# Generated by Django 4.2.23 on 2025-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.CharField(blank=True, help_text='Optional special requests or comments', max_length=90, null=True),
        ),
    ]
